"use client";

import { useState } from "react";

interface Appointment {
  id: string;
  userId: string;
  patient: {
    name: string;
  };
}

interface Doctor {
  name?: string;
  email?: string;
  phone?: string;
  specialization?: string;
  licenseNumber?: string;
  hospitalAffiliation?: string;
}

export default function PrescriptionForm({
  userId,
  appointments,
  doctor,
}: {
  userId: string;
  appointments: Appointment[];
  doctor?: Doctor;
}) {
  const [selectedAppointmentId, setSelectedAppointmentId] = useState("");
  const [medicine, setMedicine] = useState("");
  const [dosage, setDosage] = useState("");
  const [instructions, setInstructions] = useState("");
  const [loading, setLoading] = useState(false);

  const generatePrescriptionImage = async (patientName: string, appointmentId: string, doctorInfo?: Doctor): Promise<Blob> => {
    const canvas = document.createElement("canvas");
    const ctx = canvas.getContext("2d");

    if (!ctx) {
      throw new Error("Could not get canvas context");
    }

    // Use 2x scale for high DPI (crisp when zoomed)
    const scale = 2;

    // Smaller base dimensions (more reasonable size)
    const baseWidth = 600;
    const baseHeight = 800;

    // Set actual canvas size at higher resolution
    canvas.width = baseWidth * scale;
    canvas.height = baseHeight * scale;

    // Scale the context to match
    ctx.scale(scale, scale);

    // Enable text rendering hints for better quality
    ctx.textBaseline = "top";
    ctx.imageSmoothingEnabled = true;
    ctx.imageSmoothingQuality = "high";

    // Background
    ctx.fillStyle = "#ffffff";
    ctx.fillRect(0, 0, baseWidth, baseHeight);

    // Title
    ctx.fillStyle = "#000000";
    ctx.font = "bold 28px Arial";
    ctx.textAlign = "center";
    ctx.fillText("Medical Prescription", baseWidth / 2, 30);

    // Horizontal line
    ctx.strokeStyle = "#000000";
    ctx.lineWidth = 2;
    ctx.beginPath();
    ctx.moveTo(30, 50);
    ctx.lineTo(baseWidth - 30, 50);
    ctx.stroke();

    // Prescription details
    ctx.font = "14px Arial";
    ctx.textAlign = "left";
    let yPos = 70;

    ctx.fillText(`Patient Name: ${patientName}`, 30, yPos);
    yPos += 22;
    ctx.fillText(`Appointment ID: ${appointmentId}`, 30, yPos);
    yPos += 22;
    ctx.fillText(`Date: ${new Date().toLocaleDateString()}`, 30, yPos);
    yPos += 35;

    // Doctor details section
    if (doctorInfo && doctorInfo.name) {
      ctx.font = "bold 14px Arial";
      ctx.fillText("Prescribing Doctor:", 30, yPos);
      ctx.font = "14px Arial";
      yPos += 22;
      ctx.fillText(`Dr. ${doctorInfo.name}`, 50, yPos);
      yPos += 20;
      if (doctorInfo.specialization) {
        ctx.fillText(`Specialization: ${doctorInfo.specialization}`, 50, yPos);
        yPos += 20;
      }
      if (doctorInfo.licenseNumber) {
        ctx.fillText(`License Number: ${doctorInfo.licenseNumber}`, 50, yPos);
        yPos += 20;
      }
      if (doctorInfo.hospitalAffiliation) {
        ctx.fillText(`Hospital: ${doctorInfo.hospitalAffiliation}`, 50, yPos);
        yPos += 20;
      }
      yPos += 15;
    }

    // Medicine section
    ctx.font = "bold 14px Arial";
    ctx.fillText("Medicine:", 30, yPos);
    ctx.font = "14px Arial";
    yPos += 22;
    const medicineText = medicine || "N/A";
    const medicineLines = medicineText.match(/.{1,50}/g) || [medicineText];
    medicineLines.forEach((line: string) => {
      ctx.fillText(line, 50, yPos);
      yPos += 20;
    });
    yPos += 12;

    // Dosage section
    ctx.font = "bold 14px Arial";
    ctx.fillText("Dosage:", 30, yPos);
    ctx.font = "14px Arial";
    yPos += 22;
    const dosageText = dosage || "N/A";
    const dosageLines = dosageText.match(/.{1,50}/g) || [dosageText];
    dosageLines.forEach((line: string) => {
      ctx.fillText(line, 50, yPos);
      yPos += 20;
    });
    yPos += 12;

    // Instructions section
    ctx.font = "bold 14px Arial";
    ctx.fillText("Instructions:", 30, yPos);
    ctx.font = "14px Arial";
    yPos += 22;
    const instructionsText = instructions || "N/A";
    const instructionsLines = instructionsText.match(/.{1,50}/g) || [instructionsText];
    instructionsLines.forEach((line: string) => {
      ctx.fillText(line, 50, yPos);
      yPos += 20;
    });
    yPos += 30;

    // Doctor signature section
    if (doctorInfo && doctorInfo.name) {
      ctx.strokeStyle = "#000000";
      ctx.lineWidth = 1;
      ctx.beginPath();
      ctx.moveTo(30, yPos);
      ctx.lineTo(baseWidth - 30, yPos);
      ctx.stroke();
      yPos += 30;

      ctx.font = "14px Arial";
      ctx.textAlign = "left";
      ctx.fillText(`Dr. ${doctorInfo.name}`, baseWidth - 200, yPos);
      yPos += 20;
      if (doctorInfo.licenseNumber) {
        ctx.font = "12px Arial";
        ctx.fillText(`License: ${doctorInfo.licenseNumber}`, baseWidth - 200, yPos);
      }
    }

    // Footer
    ctx.font = "italic 12px Arial";
    ctx.textAlign = "center";
    ctx.fillText("Generated by CarePulse", baseWidth / 2, baseHeight - 25);

    // Convert canvas to blob with high quality
    return new Promise((resolve, reject) => {
      canvas.toBlob((blob) => {
        if (blob) {
          resolve(blob);
        } else {
          reject(new Error("Failed to convert canvas to blob"));
        }
      }, "image/png", 1.0); // Maximum quality
    });
  };

  const handleSubmit = async () => {
    if (!selectedAppointmentId) return alert("Please select an appointment.");

    setLoading(true);

    try {
      // Find the selected appointment to get the userId
      const selectedAppointment = appointments.find(appt => appt.id === selectedAppointmentId);
      const appointmentUserId = selectedAppointment ? selectedAppointment.userId : "";
      const patientName = selectedAppointment ? selectedAppointment.patient.name : "";

      // Generate prescription as image
      const imageBlob = await generatePrescriptionImage(patientName, selectedAppointmentId, doctor);
      const fileName = `prescription-${selectedAppointmentId}-${Date.now()}.png`;

      const formData = new FormData();
      formData.append("file", imageBlob, fileName);
      formData.append("userId", appointmentUserId);
      formData.append("appointmentId", selectedAppointmentId);

      const res = await fetch("/api/upload-prescription", {
        method: "POST",
        body: formData,
      });

      const data = await res.json();

      if (res.ok) {
        alert("Prescription Uploaded ✅");
        setMedicine("");
        setDosage("");
        setInstructions("");
        setSelectedAppointmentId("");
      } else {
        alert("Upload failed ❌: " + data.error);
      }
    } catch (error) {
      console.error("Error generating prescription:", error);
      alert("Failed to generate prescription image. Please try again.");
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="max-w-xl mx-auto mt-10 bg-white p-8 rounded-2xl shadow-lg space-y-6 border">
      <h2 className="text-2xl font-semibold text-gray-800">
        📝 Create Online Prescription
      </h2>

      {/* Appointment Dropdown */}
      <div>
        <label className="block text-sm font-medium text-gray-700 mb-1">
          Select Appointment
        </label>
        <select
          value={selectedAppointmentId}
          onChange={(e) => setSelectedAppointmentId(e.target.value)}
          className="w-full px-4 py-2 border rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500"
        >
          <option value="">-- Select Appointment --</option>
          {appointments.map((appt) => (
            <option key={appt.id} value={appt.id}>
              {appt.id} — {appt.patient.name}
            </option>
          ))}
        </select>
      </div>

      {/* Medicine */}
      <div>
        <label className="block text-sm font-medium text-gray-700 mb-1">
          Medicine
        </label>
        <input
          type="text"
          placeholder="e.g. Paracetamol"
          value={medicine}
          onChange={(e) => setMedicine(e.target.value)}
          className="w-full px-4 py-2 border rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500"
        />
      </div>

      {/* Dosage */}
      <div>
        <label className="block text-sm font-medium text-gray-700 mb-1">
          Dosage
        </label>
        <input
          type="text"
          placeholder="e.g. 500mg twice a day"
          value={dosage}
          onChange={(e) => setDosage(e.target.value)}
          className="w-full px-4 py-2 border rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500"
        />
      </div>

      {/* Instructions */}
      <div>
        <label className="block text-sm font-medium text-gray-700 mb-1">
          Instructions
        </label>
        <textarea
          placeholder="e.g. Take after food, for 5 days"
          value={instructions}
          onChange={(e) => setInstructions(e.target.value)}
          rows={4}
          className="w-full px-4 py-2 border rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500"
        />
      </div>

      {/* Submit Button */}
      <div className="pt-4">
        <button
          onClick={handleSubmit}
          disabled={loading}
          className="w-full bg-blue-600 text-white py-2 px-4 rounded-md hover:bg-blue-700 transition disabled:opacity-50"
        >
          {loading ? "Uploading..." : "Upload Prescription"}
        </button>
      </div>
    </div>
  );
}